In [1]:
from tensorflow.keras.preprocessing.text import one_hot

d:\Projects\End to End DL project with RNN\venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
sent=['I love my dog',
      'I love my cat',
      'You love my dog!',
      'Do you think my dog is amazing?',
      'My dog loves me more than you',
      'i am happy to see you',
      'you are my best friend'
    ]

In [3]:
sent

['I love my dog',
 'I love my cat',
 'You love my dog!',
 'Do you think my dog is amazing?',
 'My dog loves me more than you',
 'i am happy to see you',
 'you are my best friend']

In [4]:
voc_size=10000

In [5]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[9298, 1571, 8059, 4672],
 [9298, 1571, 8059, 5312],
 [3733, 1571, 8059, 4672],
 [257, 3733, 4282, 8059, 4672, 4844, 2121],
 [8059, 4672, 7345, 8285, 1738, 1534, 3733],
 [9298, 7223, 3385, 8163, 1570, 3733],
 [3733, 4047, 8059, 6999, 9712]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9298 1571 8059 4672]
 [   0    0    0    0 9298 1571 8059 5312]
 [   0    0    0    0 3733 1571 8059 4672]
 [   0  257 3733 4282 8059 4672 4844 2121]
 [   0 8059 4672 7345 8285 1738 1534 3733]
 [   0    0 9298 7223 3385 8163 1570 3733]
 [   0    0    0 3733 4047 8059 6999 9712]]


In [9]:
dim =10

In [10]:
model = Sequential()
model.add(Embedding(voc_size,dim, input_length=sent_length))
model.compile('adam','mse')

d:\Projects\End to End DL project with RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step


array([[[-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.02762136,  0.00669581,  0.0427664 ,  0.0207347 ,
          0.01363096,  0.04419104, -0.0055756 , -0.00271752,
          0.02266109,  0.04178664],
        [ 0.03713248, -0.04516014,  0.01292406,  0.00098771,
          0.00921316, -0.02660872,  0.04578711,  0.02068653,
          0.02496136,  0.03785679],
        [-0.01369029,  0.02808483,  0.02988559,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 9298, 1571, 8059, 4672], dtype=int32)

In [14]:
model.predict(embedded_docs[0].reshape(1, sent_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[[-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.0414582 ,  0.03496604,  0.0397144 , -0.0062579 ,
          0.04571408, -0.01696432, -0.01221417, -0.00130786,
         -0.04598179,  0.03813017],
        [-0.02762136,  0.00669581,  0.0427664 ,  0.0207347 ,
          0.01363096,  0.04419104, -0.0055756 , -0.00271752,
          0.02266109,  0.04178664],
        [ 0.03713248, -0.04516014,  0.01292406,  0.00098771,
          0.00921316, -0.02660872,  0.04578711,  0.02068653,
          0.02496136,  0.03785679],
        [-0.01369029,  0.02808483,  0.02988559,  0.0